<?php 
$countries_and_states = array
(                             
"Afghanistan" => array(),                        
"Albania" => array(),                            
"Algeria" => array(),                           
"Andorra" => array(),                           
"Angola" => array(),                             
"Antigua and Barbuda" => array(),             
"Argentina" => array
   (
        "Buenos Aires",
        "Catamarca",
        "Chaco",
        "Chubut",
        "Cordoba",
        "Corrientes",
        "Distrito Federal",
        "Entre Rios",
        "Formosa",
        "Jujuy",
        "La Pampa",
        "La Rioja",
        "Mendoza",
        "Misiones",
        "Neuquen",
        "Rio Negro",
        "Salta",
        "San Juan",
        "San Luis",
        "Santa Cruz",
        "Santa Fe",
        "Santiago del Estero",
        "Tierra del Fuego",
        "Tucuman"
   ),                       
"Armenia" => array(),                           
"Aruba" => array(),                         
"Australia" => array
   (
        "Australian Capital Territory",
        "New South Wales",
        "Northern Territory",
        "Queensland",
        "South Australia",
        "Tasmania",
        "Victoria",
        "Western Australia"
   ),                       
"Austria" => array
   (
        "Burgenland",
        "Carinthia",
        "Lower Austria",
        "Salzburg",
        "Styria",
        "Tyrol",
        "Upper Austria",
        "Vienna",
        "Vorarlberg"
   ),                         
"Azerbaijan" => array(),                        
"Bahamas" => array(),                           
"Bahrain" => array(),                           
"Bangladesh" => array(),                        
"Barbados" => array(),                          
"Belarus" => array(),                           
"Belgium" => array(),                           
"Belize" => array(),                           
"Benin" => array(),                             
"Bermuda" => array(),                           
"Bhutan" => array(),                         
"Bolivia" => array
   (
        "Chuquisaca",
        "Cochabamba",
        "El Beni",
        "La Paz",
        "Oruro",
        "Pando",
        "Potosi",
        "Santa Cruz",
        "Tarija"
   ),                         
"Bosnia &amp; Herzegovina" => array(),          
"Botswana" => array(),                       
"Brazil" => array
   (
        "Acre",
        "Alagoas",
        "Amapá",
        "Amazonas",
        "Bahia",
        "Ceará",
        "Distrito Federal",
        "Espírito Santo",
        "Goiás",
        "Maranhão",
        "Mato Grosso",
        "Mato Grosso do Sul",
        "Minas Gerais",
        "Paraná",
        "Paraíba",
        "Pará",
        "Pernambuco",
        "Piauí",
        "Rio de Janeiro",
        "Rio Grande do Norte",
        "Rio Grande do Sul",
        "Rondônia",
        "Roraima",
        "Santa Catarina",
        "Sergipe",
        "São Paulo",
        "Tocantins"
   ),                         
"Brunei" => array(),                            
"Bulgaria" => array(),                          
"Burkina Faso" => array(),                      
"Burma" => array(),                             
"Burundi" => array(),                           
"Cambodia" => array(),                          
"Cameroon" => array(),                      
"Canada" => array
   (
        "Alberta",
        "British Columbia",
        "Manitoba",
        "New Brunswick",
        "Newfoundland",
        "Northwest Territories",
        "Nova Scotia",
        "Nunavut",
        "Ontario",
        "Prince Edward Island",
        "Quebec",
        "Saskatchewan",
        "Yukon Territory"
   ),                          
"Cape Verde" => array(),                        
"Cayman Islands" => array(),                    
"Central African Republic" => array(),          
"Chad" => array(),                           
"Chile" => array
   (
        "Aisen",
        "Antofagasta",
        "Araucania",
        "Atacama",
        "Bio-Bio",
        "Coquimbo",
        "Libertador Bernardo O'Higgins",
        "Los Lagos",
        "Magallanes y de la Antartica",
        "Maule",
        "Region Metropolitana",
        "Tarapaca",
        "Valparaiso"
   ),                           
"China" => array
   (
        "Anhui",
        "Beijing",
        "Chongqing",
        "Fujian",
        "Gansu",
        "Guangdong",
        "Guangxi",
        "Guizhou",
        "Hainan",
        "Hebei",
        "Heilongjiang",
        "Henan",
        "Hong Kong",
        "Hubei",
        "Hunan",
        "Inner Mongolia",
        "Jiangsu",
        "Jiangxi",
        "Jilin",
        "Liaoning",
        "Ningxia",
        "Qinghai",
        "Shaanxi",
        "Shandong",
        "Shanghai",
        "Shanxi",
        "Sichuan",
        "Tianjin",
        "Tibet",
        "Xinjiang",
        "Yunnan",
        "Zhejiang"
   ),                         
"Colombia" => array
   (
        "Amazonas",
        "Antioquia",
        "Arauca",
        "Atlantico",
        "Bolivar",
        "Boyaca",
        "Caldas",
        "Caqueta",
        "Casanare",
        "Cauca",
        "Cesar",
        "Choco",
        "Cordoba",
        "Cundinamarca",
        "Distrito Capital de Bogota",
        "Guainia",
        "Guaviare",
        "Huila",
        "La Guajira",
        "Magdalena",
        "Meta",
        "Narino",
        "Norte de Santander",
        "Putumayo",
        "Quindio",
        "Risaralda",
        "San Andres y Providencia",
        "Santander",
        "Sucre",
        "Tolima",
        "Valle del Cauca",
        "Vaupes",
        "Vichada"
   ),                      
"Comoros" => array(),                           
"Congo" => array(),                             
"Costa Rica" => array(),                        
"Croatia" => array(),                        
"Cuba" => array
   (
        "Camaguey",
        "Ciego de Avila",
        "Cienfuegos",
        "Ciudad de La Habana",
        "Granma",
        "Guantanamo",
        "Holguin",
        "Isla de la Juventud",
        "La Habana",
        "Las Tunas",
        "Matanzas",
        "Pinar del Rio",
        "Sancti Spiritus",
        "Santiago de Cuba",
        "Villa Clara"
   ),                          
"Cyprus" => array(),                            
"Czech Republic" => array(),                    
"Denmark" => array(),                           
"Djibouti" => array(),                          
"Dominica" => array(),                          
"Dominican Republic" => array(),                
"Ecuador" => array(),                           
"Egypt" => array(),                             
"El Salvador" => array(),                       
"Equatorial Guinea" => array(),                 
"Eritrea" => array(),                           
"Estonia" => array(),                           
"Ethiopia" => array(),                          
"Fiji" => array(),                              
"Finland" => array(),                       
"France" => array
   (
        "Alsace",
        "Aquitaine",
        "Auvergne",
        "Basse-Normandie",
        "Bourgogne",
        "Bretagne",
        "Centre",
        "Champagne-Ardenne",
        "Corse",
        "Franche-Comté",
        "French Polynesia & Tahiti",
        "Guadeloupe",
        "Guyane",
        "Haute-Normandie",
        "Ile de France",
        "Languedoc-Roussillon",
        "Limousin",
        "Lorraine",
        "Martinique",
        "Mayotte",
        "Midi-Pyrénées",
        "Nord-Pas de Calais",
        "Nouvelle Calédonie",
        "Pays de la Loire",
        "Picardie",
        "Poitou-Charentes",
        "Provence (PACA)",
        "Rhône Alpes",
        "Réunion",
        "St Pierre et Miquelon",
        "Wallis et Futuna"
   ),                        
"French Guiana" => array(),                     
"Gabon" => array(),                             
"Gambia" => array(),                            
"Georgia" => array(),                        
"Germany" => array
   (
        "Baden-Wurttemberg",
        "Bavaria",
        "Berlin",
        "Brandenburg",
        "Bremen",
        "Hamburg",
        "Hesse",
        "Lower Saxony",
        "Mecklenburg-Western-Pomerania",
        "Northrhine-Westphalia",
        "Rhineland-Palatinate",
        "Saarland",
        "Saxony",
        "Saxony-Anhalt",
        "Schleswig-Holstein",
        "Thuringia"
   ),                      
"Ghana" => array(),                             
"Gibraltar" => array(),                         
"Greece" => array(),                            
"Grenada" => array(),                           
"Guadeloupe" => array(),                   
"Guatemala" => array
   (
        "Alta Verapaz",
        "Baja Verapaz",
        "Chimaltenango",
        "Chiquimula",
        "El Progreso",
        "Escuintla",
        "Guatemala",
        "Huehuetenango",
        "Izabal",
        "Jalapa",
        "Jutiapa",
        "Peten",
        "Quetzaltenango",
        "Quiche",
        "Retalhuleu",
        "Sacatepequez",
        "San Marcos",
        "Santa Rosa",
        "Solola",
        "Suchitepequez",
        "Totonicapan",
        "Zacapa"
   ),                     
"Guinea" => array(),                            
"Guinea-Bissau" => array(),                     
"Guyana" => array(),                            
"Haiti" => array(),                          
"Honduras" => array
   (
        "Atlantida",
        "Choluteca",
        "Colon",
        "Comayagua",
        "Copan",
        "Cortes",
        "El Paraiso",
        "Francisco Morazan",
        "Gracias a Dios",
        "Intibuca",
        "Islas de la Bahia",
        "La Paz",
        "Lempira",
        "Ocotepeque",
        "Olancho",
        "Santa Barbara",
        "Valle",
        "Yoro"
   ),                      
"Hong Kong" => array(),                         
"Hungary" => array(),                           
"Iceland" => array(),                      
"India" => array
   (
        "Andaman and Nicobar Islands",
        "Andhra Pradesh",
        "Arunachal Pradesh",
        "Assam",
        "Bihar",
        "Chandigarh",
        "Chhattisgarh",
        "Dadra and Nagar Haveli",
        "Daman and Diu",
        "Delhi",
        "Goa",
        "Gujarat",
        "Haryana",
        "Himachal Pradesh",
        "Jammu and Kashmir",
        "Jharkhand",
        "Karnataka",
        "Kerala",
        "Lakshadweep",
        "Madhya Pradesh",
        "Maharashtra",
        "Manipur",
        "Meghalaya",
        "Mizoram",
        "Nagaland",
        "Orissa",
        "Pondicherry",
        "Punjab",
        "Rajasthan",
        "Sikkim",
        "Tamil Nadu",
        "Tripura",
        "Uttar Pradesh",
        "Uttaranchal",
        "West Bengal"
   ),                        
"Indonesia" => array(),                         
"Iran" => array(),                              
"Iraq" => array(),                              
"Ireland" => array(),                           
"Israel" => array(),                        
"Italy" => array
   (
        "Abruzzi",
        "Basilicata",
        "Calabria",
        "Campania",
        "Emilia-Romagna",
        "Friuli-Venezia Giulia",
        "Lazio",
        "Liguria",
        "Lombardia",
        "Marche",
        "Molise",
        "Piemonte",
        "Puglia",
        "Sardegna",
        "Sicilia",
        "Toscana",
        "Trentino-Alto Adige",
        "Umbria",
        "Valle d'Aosta",
        "Veneto"
   ),                         
"Ivory Coast" => array(),                       
"Jamaica" => array(),                       
"Japan" => array
   (
        "Aichi",
        "Akita",
        "Aomori",
        "Chiba",
        "Ehime",
        "Fukui",
        "Fukuoka",
        "Fukushima",
        "Gifu",
        "Gunma",
        "Hiroshima",
        "Hokkaido",
        "Hyogo",
        "Ibaragi",
        "Ishikawa",
        "Iwate",
        "Kagawa",
        "Kagoshima",
        "Kanagawa",
        "Kochi",
        "Kumamoto",
        "Kyoto",
        "Mie",
        "Miyagi",
        "Miyazaki",
        "Nagano",
        "Nagasaki",
        "Nara",
        "Niigata",
        "Oita",
        "Okayama",
        "Okinawa",
        "Osaka",
        "Saga",
        "Saitama",
        "Shiga",
        "Shiman",
        "Shizuoka",
        "Tochigi",
        "Tokushima",
        "Tokyo",
        "Tottori",
        "Toyama",
        "Wakayama",
        "Yamagata",
        "Yamaguchi",
        "Yamanashi"
   ),                         
"Jersey" => array(),                            
"Jordan" => array(),                            
"Kazakhstan" => array(),                        
"Kenya" => array(),                             
"Kuwait" => array(),                            
"Kyrgyzstan" => array(),                        
"Laos" => array(),                              
"Latvia" => array(),                            
"Lebanon" => array(),                           
"Lesotho" => array(),                           
"Liberia" => array(),                           
"Libya" => array(),                             
"Liechtenstein" => array(),                     
"Lithuania" => array(),                         
"Luxembourg" => array(),                        
"Macau" => array(),                             
"Macedonia" => array(),                         
"Madagascar" => array(),                        
"Malawi" => array(),                        
"Malaysia" => array
   (
        "Johor",
        "Kedah",
        "Kelantan",
        "Kuala Lumpur",
        "Labuan",
        "Melaka",
        "Negeri Sembilan",
        "Pahang",
        "Perak",
        "Perlis",
        "Pulau Pinang",
        "Putrajaya",
        "Sabah",
        "Sarawak",
        "Selangor",
        "Terengganu"
   ),                      
"Maldives" => array(),                          
"Mali" => array(),                              
"Malta" => array(),                             
"Martinique" => array(),                        
"Mauritania" => array(),                        
"Mauritius" => array(),                    
"Mexico" => array
   (
     "Aguascalientes",
        "Baja California Norte",
        "Baja California Sur",
        "Campeche",
        "Chiapas",
        "Chihuahua",
        "Coahuila de Zaragoza",
        "Colima",
        "Distrito Federal",
        "Durango",
        "Estado de México",
        "Guanajuato",
        "Guerrero",
        "Hidalgo",
        "Jalisco",
        "Michoacán",
        "Morelos",
        "Nayarit",
        "Nuevo León",
        "Oaxaca",
        "Puebla",
        "Querétaro",
        "Quintana Roo",
        "San Luis Potosí",
        "Sinaloa",
        "Sonora",
        "Tabasco",
        "Tamaulipas",
        "Tlaxcala",
        "Veracruz",
        "Yucatán",
        "Zacatecas"
   ),                        
"Moldova" => array(),                           
"Monaco" => array(),                            
"Mongolia" => array(),                          
"Morocco" => array(),                           
"Mozambique" => array(),                       
"Namibia" => array(),                           
"Nepal" => array(),                             
"Netherlands" => array(),                       
"Netherlands Antilles" => array(),              
"New Zealand" => array(),                       
"Nicaragua" => array(),                         
"Niger" => array(),                         
"Nigeria" => array
   (
        "Abia",
        "Adamawa",
        "Akwa Ibom",
        "Anambra",
        "Bauchi",
        "Bayelsa",
        "Benue",
        "Borno",
        "Cross River",
        "Delta",
        "Ebonyi",
        "Edo",
        "Ekiti",
        "Enugu",
        "Gombe",
        "Imo",
        "Jigawa",
        "Kaduna",
        "Kano ",
        "Katsina",
        "Kebbi",
        "Kogi",        
        "Kwara",
        "Lagos",
        "Nasarawa",
        "Niger",
        "Ogun",
        "Ondo",
        "Osun ",
        "Oyo",
        "Plateau",
        "Rivers",
        "Sokoto",
        "Taraba",
        "Yobe",
        "Zamfara ",
        "FCT (Abuja)"
   ),                       
"North Korea" => array(),                       
"Norway" => array(),                            
"Oman" => array(),                              
"Pakistan" => array(),                     
"Panama" => array
   (
        "Bocas del Toro",
        "Chiriqui",
        "Cocle",
        "Colon",
        "Darien",
        "Embera",
        "Herrera",
        "Kuna de Madungandi",
        "Kuna de Wargandi",
        "Kuna Yala (San Blas)",
        "Los Santos",
        "Ngobe Bugle",
        "Panama",
        "Veraguas"
   ),
"Paraguay" => array(),
"Peru" => array
   (
        "Amazonas",
        "Ancash",
        "Apurimac",
        "Arequipa",
        "Ayacucho",
        "Cajamarca",
        "Callao",
        "Cusco",
        "Huancavelica",
        "Huanuco",
        "Ica",
        "Junin",
        "La Libertad",
        "Lambayeque",
        "Lima",
        "Loreto",
        "Madre de Dios",
        "Moquegua",
        "Pasco",
        "Piura",
        "Puno",
        "San Martin",
        "Tacna",
        "Tumbes",
        "Ucayali"
   ), 
"Philippines" => array
   (
        "Bicol",
        "Cagayan",
        "Caraga",
        "Central Luzon",
        "Central Mindanao",
        "Central Visayas",
        "Cordillera",
        "Eastern Visayas",
        "Ilocos",
        "Muslim Mindanao",
        "National Capital Region",
        "Northern Mindanao",
        "Southern Mindanao",
        "Southern Tagalog",
        "Western Mindanao",
        "Western Visayas"
   ),  
"Poland" => array(),  
"Portugal" => array
   (
        "Aveiro",
        "Azores",
        "Beja",
        "Braga",
        "Braganca",
        "Castelo Branco",
        "Coimbra",
        "Evora",
        "Faro",
        "Guarda",
        "Leiria",
        "Lisboa",
        "Madeira",
        "Portalegre",
        "Porto",
        "Santarem",
        "Setubal",
        "Viana do Castelo",
        "Vila Real",
        "Viseu"
   ),  
"Qatar" => array(), 
"Romania" => array(),  
"Russia" => array(),  
"Rwanda" => array(),  
"San Marino" => array(),  
"Sao Tome &amp; Principe" => array(),  
"Saudi Arabia" => array(),  
"Senegal" => array(),  
"Serbia &amp; Montenegro" => array(),  
"Seychelles" => array(),  
"Sierra Leone" => array(),  
"Singapore" => array(),  
"Slovakia" => array(),  
"Slovenia" => array(),  
"Somalia" => array(),  
"South Africa" => array(),  
"South Korea" => array
   (
        "Ch'ungch'ong-bukto",
        "Ch'ungch'ong-namdo",
        "Cheju-do",
        "Cholla-bukto",
        "Cholla-namdo",
        "Inch'on-gwangyoksi",
        "Kangwon-do",
        "Kwangju-gwangyoksi",
        "Kyonggi-do",
        "Kyongsang-bukto",
        "Kyongsang-namdo",
        "Pusan-gwangyoksi",
        "Soul-t'ukpyolsi",
        "Taegu-gwangyoksi",
        "Taejon-gwangyoksi",
        "Ulsan-gwangyoksi"
   ), 
"Spain" => array
   (
        "Andalucia",
        "Aragon",
        "Asturias",
        "Baleares",
        "Canarias",
        "Cantabria",
        "Castilla-La Mancha",
        "Castilla-Leon",
        "Cataluna",
        "Comunidad Valenciana",
        "Extremadura",
        "Galicia",
        "La Rioja",
        "Madrid",
        "Murcia",
        "Navarra",
        "Pais Vasco"
   ),  
"Sri Lanka" => array(),  
"St. Kitts &amp; Nevis" => array(),  
"St. Lucia" => array(),  
"St. Vincent &amp; the Grenadines" => array(),  
"Sudan" => array(),  
"Suriname" => array(),  
"Swaziland" => array(),  
"Sweden" => array(), 
"Switzerland" => array
   (
       "Aargau",
       "Appenzell Ausserrhoden",
       "Appenzell Innerrhoden",
       "Basel-Land",
       "Basel-Stadt",
       "Bern",
       "Fribourg",
       "Geneva",
       "Glarus",
       "Graubunden",
       "Jura",
       "Lucerne",
       "Neuchatel",
       "Nidwalden",
       "Obwalden",
       "Schaffhausen",
       "Schwyz",
       "Solothurn",
       "St. Gallen",
       "Thurgau",
       "Ticino",
       "Uri",
       "Valais",
       "Vaud",
       "Zug",
       "Zurich"
   ),  
"Syria" => array(), 
"Taiwan" => array
   (
        "Kaohsiung",
        "Taipei",
        "Taiwan"
   ),  
"Tajikistan" => array(),  
"Tanzania" => array(),  
"Thailand" => array(),  
"Togo" => array(),  
"Trinidad and Tobago" => array(),  
"Tunisia" => array(),  
"Turkey" => array(),  
"Turkmenistan" => array(),  
"Turks and Caicos Islands" => array(), 
"Uganda" => array(),  
"Ukraine" => array(),  
"United Arab Emirates" => array(),  
"United Kingdom" => array
   (
       "England - Bath Avon",
       "England - Bedfordshire",
       "England - Berkshire",
       "England - Brighton and Hove",
       "England - Bristol",
       "England - Buckinghamshire",
       "England - Cambridgeshire",
       "England - Channel Isles",
       "England - Cheshire",
       "England - Cornwall",
       "England - County Durham",
       "England - Cumbria",
       "England - Derbyshire",
       "England - Devon",
       "England - Dorset",
       "England - Essex",
       "England - Gloucestershire",
       "England - Hampshire",
       "England - Herefordshire",
       "England - Hertfordshire",
       "England - Huntingdonshire",
       "England - Isle of Wight",
       "England - Isles of Scilly",
       "England - Kent",
       "England - Lancashire",
       "England - Leicestershire",
       "England - Lincolnshire",
       "England - London",
       "England - Manchester",
       "England - Merseyside",
       "England - Middlesex",
       "England - Norfolk",
       "England - Northamptonshire",
       "England - Northumberland",
       "England - Nottinghamshire",
       "England - Oxfordshire",
       "England - Rutland",
       "England - Shropshire",
       "England - Somerset",
       "England - Staffordshire",
       "England - Suffolk",
       "England - Surrey",
       "England - Sussex",
       "England - Tyne and Wear",
       "England - Warwickshire",
       "England - West Midlands",
       "England - Westmorland",
       "England - Wiltshire",
       "England - Worcestershire",
       "England - Yorkshire",
       "Isle of Man - Isle of Man",
       "N. Ireland - Antrim",
       "N. Ireland - Armagh",
       "N. Ireland - Belfast",
       "N. Ireland - Down",
       "N. Ireland - Fermanagh",
       "N. Ireland - Londonderry",
       "N. Ireland - Tyrone",
       "Scotland - Aberdeenshire",
       "Scotland - Angus",
       "Scotland - Argyllshire",
       "Scotland - Ayrshire",
       "Scotland - Banffshire",
       "Scotland - Berwickshire",
       "Scotland - Buteshire",
       "Scotland - Caithness",
       "Scotland - Clackmannanshire",
       "Scotland - Dumfriesshire",
       "Scotland - Dunbartonshire",
       "Scotland - Dundee City",
       "Scotland - Edinburgh",
       "Scotland - Falkirk",
       "Scotland - Fife",
       "Scotland - Highland",
       "Scotland - Inverness-shire",
       "Scotland - Isle of Islay",
       "Scotland - Isle of Lewis",
       "Scotland - Isle of Skye",
       "Scotland - Kincardineshire",
       "Scotland - Kinross-Shire",
       "Scotland - Kirkcudbrightshire",
       "Scotland - Lanarkshire",
       "Scotland - Midlothian",
       "Scotland - Morayshire",
       "Scotland - Nairnshire",
       "Scotland - Orkney",
       "Scotland - Peeblesshire",
       "Scotland - Perthshire",
       "Scotland - Renfrewshire",
       "Scotland - Ross-shire",
       "Scotland - Roxburghshire",
       "Scotland - Selkirkshire",
       "Scotland - Shetland",
       "Scotland - Stirlingshire",
       "Scotland - Sutherland",
       "Scotland - West Lothian",
       "Scotland - Western Isles",
       "Scotland - Wigtownshire",
       "Wales - Anglesey",
       "Wales - Brecknockshire",
       "Wales - Caernarfonshire",
       "Wales - Cardiff",
       "Wales - Cardiganshire",
       "Wales - Carmarthenshire",
       "Wales - Ceredigion",
       "Wales - Denbighshire",
       "Wales - Flintshire",
       "Wales - Glamorgan",
       "Wales - Gwynedd",
       "Wales - Merioneth",
       "Wales - Monmouthshire",
       "Wales - Montgomeryshire",
       "Wales - Newport",
       "Wales - Pembrokeshire",
       "Wales - Radnorshire",
       "Wales - Swansea"
   ),  
"United States" => array
   (
        "Alabama", 
        "Alaska", 
        "American Samoa", 
        "Arizona", 
        "Arkansas", 
        "California",
        "Colorado", 
        "Connecticut", 
        "Delaware", 
        "District of Columbia", 
        "Florida", 
        "Georgia", 
        "Guam", 
        "Hawaii", 
        "Idaho", 
        "Illinois", 
        "Indiana", 
        "Iowa", 
        "Kansas", 
        "Kentucky", 
        "Louisiana", 
        "Maine", 
        "Maryland", 
        "Massachusetts", 
        "Michigan", 
        "Minnesota", 
        "Mississippi", 
        "Missouri", 
        "Montana", 
        "Nebraska", 
        "Nevada", 
        "New Hampshire", 
        "New Jersey", 
        "New Mexico", 
        "New York", 
        "North Carolina", 
        "North Dakota", 
        "Northern Mariana Islands", 
        "Ohio", 
        "Oklahoma", 
        "Oregon", 
        "Pennsylvania", 
        "Puerto Rico", 
        "Rhode Island", 
        "South Carolina", 
        "South Dakota", 
        "Tennessee", 
        "Texas", 
        "Utah", 
        "Vermont", 
        "Virgin Islands", 
        "Virginia", 
        "Washington", 
        "West Virginia", 
        "Wisconsin", 
        "Wyoming" 
   ),  
"Uruguay" => array(),  
"Uzbekistan" => array(),  
"Venezuela" => array
   (
       "Amazonas", 
        "Anzoategui", 
        "Apure", 
        "Aragua", 
        "Barinas", 
        "Bolivar", 
        "Carabobo", 
        "Cojedes", 
        "Delta Amacuro", 
        "Dependencias Federales", 
        "Distrito Federal", 
        "Falcon", 
        "Guarico", 
        "Lara", 
        "Merida", 
        "Miranda", 
        "Monagas", 
        "Nueva Esparta", 
        "Portuguesa", 
        "Sucre", 
        "Tachira", 
        "Trujillo", 
        "Vargas", 
        "Yaracuy", 
        "Zulia" 
   ), 
"Vietnam" => array(),  
"Western Sahara" => array(),  
"Yemen" => array(),  
"Zambia" => array(),  
"Zimbabwe" => array(), 

);