football:, basketball:, baseball:, tennis:, table-tennis:, volley-ball:, 
premier-league:, la-liga:, ligue-1:, bundesliga:, serie-a:, npfl:,
arsenal:, man-u:, everton:, stoke-city:, fc-barcelona:, 
jquery:, javascript:, php:, html:, css:,
web-design:, open-graph:, oembed:,
facebook:, twitter:, google:, google-plus:, instagram:, you-tube:, tumblr:, reddit:,
mysql:, mssql:, mongo-db:, maria-db:, 
express-js:, angular-js:, node-js:,
microsoft:, yahoo:, google:, money:,
wamp:, xampp:,
