var jsFiles = [
                libPath + 'floatingWindow',
                libPath + 'mouseManager',
                libPath + 'eventManager', 
                libPath + 'contextMenuManager',
                libPath + 'imageManager', 
                libPath + 'styleManager', 
                libPath + 'errorManager', 
                libPath + 'effectsManager',
                coreScriptsPath + 'async/buddiesOnline', 
                coreScriptsPath + 'async/chatHandler.js',
                coreScriptsPath + 'async/buddiesHandler.js',
                coreScriptsPath + 'async/dbRoomsHandler.js',
                coreScriptsPath + 'client/IMWin',
                coreScriptsPath + 'client/PMWin',
                coreScriptsPath + 'client/chatRoomWin',
                coreScriptsPath + 'client/emotes',
                coreScriptsPath + 'client/themeSetter',
                coreScriptsPath + 'client/messengerCMenuFunctions',
                coreScriptsPath + 'client/init/chatInitialiser',
                coreScriptsPath + 'client/init/IMWinInitialiser', 
                coreScriptsPath + 'client/init/chatRoomWinInitialiser.js',
                coreScriptsPath + 'client/init/PMWinInitialiser.js',
                coreScriptsPath + 'client/imageSwapFunctions.js', 
                coreScriptsPath + 'client/textEditFunctions.js',  
                coreScriptsPath + 'chatStateManagers/client/chatStateUpdateHandlers',
                coreScriptsPath + 'chatStateManagers/client/detachManager',
                coreScriptsPath + 'chatStateManagers/client/loadManager', 
                coreScriptsPath + 'chatStateManagers/client/closedWindowManager', 
                coreScriptsPath + 'chatStateManagers/client/chatResizeManager',        
                coreScriptsPath + 'chatStateManagers/client/chatStateRegistrars.js'
               ]
 includeJS(jsFiles);